name: 💀 DESTROY Backend

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

defaults:
  run:
    working-directory: backend

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      timeout-minutes: 2
      run: |
        terraform init
    
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
